/**
 * Builds the docs Changelog page from the CHANGELOG.md files Changesets
 * writes into each published package on release.
 *
 * The packages version in lockstep and Changesets repeats a changeset's
 * summary in every affected package's changelog, so entries are merged by
 * version and deduplicated by text. "Updated dependencies" noise is dropped.
 *
 * Runs before `astro build` / `astro dev`; the output is gitignored.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");
const OUT = join(ROOT, "apps/docs/src/content/docs/reference/changelog.md");

const PACKAGE_DIRS = [
  "apps/desktop",
  "packages/worker",
  "packages/orchestrator",
  "packages/sandbox",
  "packages/shared",
  "apps/app",
];

const BUMP_ORDER = ["Major Changes", "Minor Changes", "Patch Changes"] as const;
type Bump = (typeof BUMP_ORDER)[number];

/** version -> bump -> ordered, deduplicated entries */
const versions = new Map<string, Map<Bump, string[]>>();

function parseChangelog(text: string) {
  let version: string | null = null;
  let bump: Bump | null = null;
  let entry: string[] = [];

  const flush = () => {
    if (!version || !bump || entry.length === 0) {
      entry = [];
      return;
    }
    // Dependency bumps between the lockstep packages are noise here.
    const joined = entry
      .join("\n")
      .trimEnd()
      .replace(/^- [0-9a-f]{7,40}: /, "- ");
    entry = [];
    if (joined.startsWith("- Updated dependencies")) return;

    const byBump = versions.get(version) ?? new Map<Bump, string[]>();
    versions.set(version, byBump);
    const entries = byBump.get(bump) ?? [];
    byBump.set(bump, entries);
    if (!entries.includes(joined)) entries.push(joined);
  };

  for (const line of text.split("\n")) {
    const versionHeading = line.match(/^## (\d+\.\d+\.\d+.*)$/);
    if (versionHeading) {
      flush();
      version = versionHeading[1]!.trim();
      bump = null;
      continue;
    }
    const bumpHeading = line.match(/^### (Major|Minor|Patch) Changes$/);
    if (bumpHeading) {
      flush();
      bump = `${bumpHeading[1]} Changes` as Bump;
      continue;
    }
    if (line.startsWith("- ")) {
      flush();
      entry = [line];
    } else if (entry.length > 0 && (line.startsWith("  ") || line === "")) {
      entry.push(line);
    }
  }
  flush();
}

for (const dir of PACKAGE_DIRS) {
  const file = join(ROOT, dir, "CHANGELOG.md");
  if (existsSync(file)) parseChangelog(readFileSync(file, "utf8"));
}

const byVersionDesc = [...versions.keys()].sort((a, b) => {
  const pa = a.split(/[.-]/).map(Number);
  const pb = b.split(/[.-]/).map(Number);
  for (let i = 0; i < 3; i++) {
    if ((pb[i] ?? 0) !== (pa[i] ?? 0)) return (pb[i] ?? 0) - (pa[i] ?? 0);
  }
  return b.localeCompare(a);
});

const sections = byVersionDesc.map((version) => {
  const byBump = versions.get(version)!;
  const parts = BUMP_ORDER.filter((bump) => byBump.has(bump)).map(
    (bump) => `### ${bump}\n\n${byBump.get(bump)!.join("\n")}`,
  );
  return `## ${version}\n\n${parts.join("\n\n")}`;
});

const body =
  sections.length > 0
    ? sections.join("\n\n")
    : "No releases have been published yet. Release notes appear here once the first Changesets release ships.";

const page = `---
title: Changelog
description: Release notes for the brevi packages, one entry per lockstep version.
---

<!-- Generated by scripts/build-changelog.ts from the packages' CHANGELOG.md files. Do not edit. -->

Each version below covers Mission Control, its bundled orchestrator and renderer, and the matching worker release.

${body}
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, page);
console.log(`changelog: ${byVersionDesc.length} version(s) -> ${OUT}`);
