import { readFile, rm } from "node:fs/promises";
import { join } from "node:path";
import { resolveFirecrackerImages, WORKSPACES_DIR, type FirecrackerConfig } from "@brevi/shared";
import { execa } from "execa";
import { fileExists, isReadWritable, resolveBinary, resolveFirecrackerBinary } from "../host.js";
import type { CreateSandboxOptions, Sandbox, SandboxProvider } from "../types.js";
import { ensureRootfs, locateRootfs } from "./rootfs.js";
import { ensureGuestWorkspace, FirecrackerSandbox } from "./sandbox.js";
import { SSH_KEY_PATH, waitForSsh, type SshTarget } from "./ssh.js";
import { bootMicroVm } from "./vm.js";

/** Host tools the provider shells out to for networking and file transfer. */
const REQUIRED_TOOLS = ["ip", "ssh", "tar"];

const SETUP_DOC = "packages/sandbox/README.md";

/**
 * The cheap host-level gates: platform, KVM access, the firecracker binary, required host
 * tools, and the kernel image. Deliberately excludes the rootfs and ssh key so callers that
 * need to decide whether a (possibly multi-GB) rootfs download is worth attempting can check
 * these first, without ever double-reporting them once the fuller checks below run too.
 */
export async function collectFirecrackerBaseProblems(config: FirecrackerConfig): Promise<string[]> {
  const problems: string[] = [];

  if (process.platform !== "linux") {
    problems.push(
      `firecracker needs KVM, which only exists on Linux (this host is ${process.platform}); use the "process" provider or run brevi inside a Linux VM`,
    );
  }
  if (!(await isReadWritable("/dev/kvm"))) {
    problems.push(
      '/dev/kvm is not readable and writable by this user; load the kvm module and add yourself to the "kvm" group',
    );
  }
  if ((await resolveFirecrackerBinary(config.binary)) === undefined) {
    problems.push(
      `the firecracker binary "${config.binary}" was not found on PATH or in ~/.brevi/bin; install it or set sandbox.firecracker.binary`,
    );
  }
  for (const tool of REQUIRED_TOOLS) {
    if ((await resolveBinary(tool)) === undefined) {
      problems.push(`the "${tool}" command was not found on PATH`);
    }
  }
  const { kernelImage } = resolveFirecrackerImages(config);
  if (!(await fileExists(kernelImage))) {
    problems.push(`kernel image ${kernelImage} is missing`);
  }
  // The rootfs is deliberately not checked here: these are the cheap checks that gate
  // whether auto mode may resolve an image at all, and resolution (cache hit, download,
  // or from-source build) happens later in ensureRootfs. The ssh keypair is checked in
  // collectFirecrackerProblems below, which is the full preflight.

  return problems;
}

/**
 * Ssh keypair problems, shared between collectFirecrackerProblems and provider selection.
 * Checks both halves: the private key must exist and parse, and its public sidecar must
 * exist and match it. The sidecar is what readAuthorizedKeysArg (./vm.ts) injects into the
 * guest at boot; a prebuilt image bakes in no key of its own, so a missing or mismatched
 * sidecar would boot a VM that accepts no key at all and dies as an opaque ssh timeout.
 */
export async function collectSshKeyProblems(keyPath: string = SSH_KEY_PATH): Promise<string[]> {
  if (!(await fileExists(keyPath))) {
    return [
      `ssh key ${keyPath} is missing; it is generated by "brevi setup" (or by packages/sandbox/scripts/build-rootfs.sh for from-source images, where it must match the key baked into the rootfs)`,
    ];
  }
  const pubPath = `${keyPath}.pub`;
  let derived: string | undefined;
  try {
    derived = (await execa("ssh-keygen", ["-y", "-P", "", "-f", keyPath])).stdout.trim();
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      // No ssh-keygen on this host; the pair can't be validated beyond existence.
      derived = undefined;
    } else {
      return [
        `ssh key ${keyPath} is unreadable or not a valid private key; delete it and run "brevi setup" to generate a fresh keypair`,
      ];
    }
  }
  if (!(await fileExists(pubPath))) {
    return [
      `ssh public key ${pubPath} is missing; without it the host's key is never injected into the guest at boot and VMs reject every connection; run "brevi setup" to reconstruct it`,
    ];
  }
  if (derived !== undefined) {
    let published: string;
    try {
      published = await readFile(pubPath, "utf8");
    } catch {
      return [`ssh public key ${pubPath} is unreadable; delete it and run "brevi setup" to reconstruct it`];
    }
    if (!sshPublicKeysMatch(derived, published)) {
      return [
        `ssh public key ${pubPath} does not match the private key ${keyPath}; VMs booted with it would reject every connection; delete ${pubPath} and run "brevi setup" to reconstruct it from the private key`,
      ];
    }
  }
  return [];
}

/** Compares the type and key-material fields, ignoring the trailing comment. */
function sshPublicKeysMatch(a: string, b: string): boolean {
  const fields = (key: string): string => key.trim().split(/\s+/).slice(0, 2).join(" ");
  return fields(a) !== "" && fields(a) === fields(b);
}

/**
 * Everything stopping this host from booting Firecracker microVMs with the given
 * config, as human-readable problems. Empty means the provider is ready to run. Never
 * downloads a rootfs image; locateRootfs only resolves what is already local or cached.
 * `cliVersion` is the @brevi/cli release whose cache entry counts as resolvable.
 */
export async function collectFirecrackerProblems(
  config: FirecrackerConfig,
  cliVersion: string,
): Promise<string[]> {
  const problems = await collectFirecrackerBaseProblems(config);

  // locateRootfs is cache-aware: it also accepts a downloaded image under
  // ~/.brevi/cache/rootfs, not just a from-source build at config.rootfs.
  const rootfs = await locateRootfs(config, { cliVersion });
  if (rootfs.path === undefined) {
    problems.push(...rootfs.problems);
  }
  problems.push(...(await collectSshKeyProblems()));

  return problems;
}

/**
 * Networking problems that block Firecracker regardless of the base preflight: missing
 * tap devices and disabled IPv4 forwarding. Skipped on non-Linux hosts; the base checks
 * already report the platform problem there.
 */
export async function collectFirecrackerNetworkProblems(concurrency: number): Promise<string[]> {
  if (process.platform !== "linux") return [];

  const problems: string[] = [];
  const pointer =
    "run brevi setup's networking step or packages/sandbox/scripts/setup-network.sh (tap devices and rules do not persist across reboots, so this is needed again after every restart)";

  // Root creates tap devices on demand (see ensureTapDevice in ./network.ts), so missing
  // taps are only a problem for a non-root process.
  if (process.getuid?.() !== 0) {
    const missing: string[] = [];
    for (let i = 0; i < concurrency; i++) {
      if (!(await fileExists(`/sys/class/net/brevi-tap${i}`))) missing.push(`brevi-tap${i}`);
    }
    if (missing.length > 0) {
      problems.push(`tap devices missing: ${missing.join(", ")}; ${pointer}`);
    }
  }

  if (!(await ipForwardEnabled())) {
    problems.push(`IPv4 forwarding is disabled; ${pointer}`);
  }

  return problems;
}

async function ipForwardEnabled(): Promise<boolean> {
  try {
    return (await readFile("/proc/sys/net/ipv4/ip_forward", "utf8")).trim() === "1";
  } catch {
    return false;
  }
}

/**
 * The complete Firecracker preflight: everything collectFirecrackerProblems checks, plus
 * networking. This is what provider selection and `brevi doctor` should use; auto-mode and
 * explicit-provider validation both need the network checks, not just the base ones.
 */
export async function collectFirecrackerPreflightProblems(
  config: FirecrackerConfig,
  concurrency: number,
  cliVersion: string,
): Promise<string[]> {
  return [
    ...(await collectFirecrackerProblems(config, cliVersion)),
    ...(await collectFirecrackerNetworkProblems(concurrency)),
  ];
}

/**
 * Runs each sandbox as a Firecracker microVM: real kernel-level isolation, at the cost
 * of requiring a Linux host with KVM plus a prepared kernel and rootfs image.
 */
export class FirecrackerProvider implements SandboxProvider {
  readonly name = "firecracker" as const;
  readonly #config: FirecrackerConfig;
  readonly #cliVersion: string;
  readonly #log: (line: string) => void;

  /**
   * `options.cliVersion` is the @brevi/cli release whose cached prebuilt image this
   * provider may boot from (and redownload on corruption); without it only a from-source
   * or custom-configured image resolves. `config` is held by reference, never cloned: the
   * dashboard mutates vcpus/mem on this same object between boots (see the comment in
   * vm.ts configure()), and a resolved rootfs path is never written back into
   * config.rootfs, which would persist a cache path into ~/.brevi/config.json.
   */
  constructor(config: FirecrackerConfig, options?: { cliVersion?: string; log?: (line: string) => void }) {
    this.#config = config;
    this.#cliVersion = options?.cliVersion ?? "0.0.0";
    this.#log = options?.log ?? ((): void => {});
  }

  async ensureAvailable(): Promise<void> {
    const problems = await collectFirecrackerProblems(this.#config, this.#cliVersion);
    if (problems.length === 0) return;
    const remedy =
      process.platform === "linux"
        ? `Run "brevi setup" to provision this host, or see ${SETUP_DOC} for manual setup.`
        : `See ${SETUP_DOC} for what the firecracker provider needs.`;
    throw new Error(
      `The firecracker sandbox provider cannot run on this host:\n${problems
        .map((problem) => `  - ${problem}`)
        .join("\n")}\n${remedy}`,
    );
  }

  /**
   * Resolves and verifies the base image at boot time, not once at startup: a cached image
   * corrupted while the daemon runs must be caught by its checksum here and redownloaded,
   * not copied into the workspace to fail later as an opaque VM boot error.
   */
  async #resolveBootImage(): Promise<string> {
    const resolved = await ensureRootfs(this.#config, {
      cliVersion: this.#cliVersion,
      download: true,
      log: this.#log,
    });
    if (resolved.path === undefined) {
      throw new Error(
        `no usable rootfs image to boot from:\n${resolved.problems.map((problem) => `  - ${problem}`).join("\n")}`,
      );
    }
    return resolved.path;
  }

  async create(options: CreateSandboxOptions): Promise<Sandbox> {
    const rootDir = join(WORKSPACES_DIR, options.id);
    const rootfsImage = await this.#resolveBootImage();
    const vm = await bootMicroVm({ id: options.id, rootDir, config: this.#config, rootfsImage });
    try {
      const target: SshTarget = {
        keyPath: SSH_KEY_PATH,
        host: vm.network.guestIp,
        user: "root",
      };
      await waitForSsh(target);
      await ensureGuestWorkspace(target);
      return new FirecrackerSandbox({ id: options.id, vm, target, env: options.env ?? {}, rootDir });
    } catch (error) {
      await vm.stop();
      await rm(rootDir, { recursive: true, force: true });
      throw error;
    }
  }

  async rehydrate(options: CreateSandboxOptions): Promise<Sandbox> {
    const rootDir = join(WORKSPACES_DIR, options.id);
    // No base image needed: the retained disk is booted as-is. bootMicroVm validates the
    // disk's recorded rootfs version against this build's before booting, so a disk
    // created under an older contract is refused with an actionable error instead of
    // failing later as an ssh timeout.
    const vm = await bootMicroVm({
      id: options.id,
      rootDir,
      config: this.#config,
      reuseRootfs: true,
    });
    try {
      const target: SshTarget = {
        keyPath: SSH_KEY_PATH,
        host: vm.network.guestIp,
        user: "root",
      };
      await waitForSsh(target);
      return new FirecrackerSandbox({ id: options.id, vm, target, env: options.env ?? {}, rootDir });
    } catch (error) {
      // Keep the retained rootfs on disk so a failed resume can be retried.
      await vm.stop();
      throw error;
    }
  }

  async discard(id: string): Promise<void> {
    await rm(join(WORKSPACES_DIR, id), { recursive: true, force: true });
  }
}
