import { open, readFile, rm, stat } from "node:fs/promises";
import { join } from "node:path";
import { resolveFirecrackerImages, WORKSPACES_DIR, type FirecrackerConfig } from "@brevi/shared";
import { fileExists, isReadWritable, resolveBinary, resolveFirecrackerBinary } from "../host.js";
import type { CreateSandboxOptions, Sandbox, SandboxProvider } from "../types.js";
import { ensureGuestWorkspace, FirecrackerSandbox } from "./sandbox.js";
import { SSH_KEY_PATH, waitForSsh, type SshTarget } from "./ssh.js";
import { bootMicroVm } from "./vm.js";

/** Host tools the provider shells out to for networking and file transfer. */
const REQUIRED_TOOLS = ["ip", "ssh", "tar"];

const SETUP_DOC = "packages/sandbox/README.md";

const REBUILD_HINT =
  "rebuild it with packages/sandbox/scripts/build-rootfs.sh (or brevi setup)";

/**
 * Bumped whenever the rootfs contract changes (a new required guest tool, a layout
 * change, etc.); must match the version packages/sandbox/scripts/build-rootfs.sh
 * writes into rootfs.ext4.manifest.json.
 */
export const ROOTFS_MANIFEST_VERSION = 1;

/** Byte offset of the ext4 superblock magic (0xEF53, little-endian) from the start of the image. */
const EXT4_MAGIC_OFFSET = 1080;
const EXT4_MAGIC_BYTES = Buffer.from([0x53, 0xef]);

/**
 * Everything stopping this host from booting Firecracker microVMs with the given
 * config, as human-readable problems. Empty means the provider is ready to run.
 */
export async function collectFirecrackerProblems(config: FirecrackerConfig): Promise<string[]> {
  const problems: string[] = [];

  if (process.platform !== "linux") {
    problems.push(
      `firecracker needs KVM, which only exists on Linux (this host is ${process.platform}); use the "process" provider or run brevi inside a Linux VM`,
    );
  }
  if (!(await isReadWritable("/dev/kvm"))) {
    problems.push(
      '/dev/kvm is not readable and writable by this user; load the kvm module and add yourself to the "kvm" group',
    );
  }
  if ((await resolveFirecrackerBinary(config.binary)) === undefined) {
    problems.push(
      `the firecracker binary "${config.binary}" was not found on PATH or in ~/.brevi/bin; install it or set sandbox.firecracker.binary`,
    );
  }
  for (const tool of REQUIRED_TOOLS) {
    if ((await resolveBinary(tool)) === undefined) {
      problems.push(`the "${tool}" command was not found on PATH`);
    }
  }
  const { kernelImage, rootfs } = resolveFirecrackerImages(config);
  if (!(await fileExists(kernelImage))) {
    problems.push(`kernel image ${kernelImage} is missing`);
  }
  if (!(await fileExists(rootfs))) {
    problems.push(
      `rootfs image ${rootfs} is missing; build it with packages/sandbox/scripts/build-rootfs.sh`,
    );
  } else {
    problems.push(...(await collectRootfsProblems(rootfs)));
  }
  if (!(await fileExists(SSH_KEY_PATH))) {
    problems.push(
      `ssh key ${SSH_KEY_PATH} is missing; it is generated by packages/sandbox/scripts/build-rootfs.sh and must match the key baked into the rootfs`,
    );
  }

  return problems;
}

/**
 * Validates an existing rootfs file: not empty, looks like ext4, and has a
 * current build manifest. Exported so `brevi setup` can offer a rebuild for an
 * image that exists but is invalid or outdated, not just for a missing one.
 */
export async function collectRootfsProblems(rootfs: string): Promise<string[]> {
  const problems: string[] = [];

  let size: number;
  try {
    size = (await stat(rootfs)).size;
  } catch {
    problems.push(`rootfs image ${rootfs} is not readable; ${REBUILD_HINT}`);
    return problems;
  }
  if (size === 0) {
    problems.push(`rootfs image ${rootfs} is empty; ${REBUILD_HINT}`);
    return problems;
  }

  if (!(await looksLikeExt4(rootfs))) {
    problems.push(`rootfs image ${rootfs} does not look like a valid ext4 image; ${REBUILD_HINT}`);
  }

  const manifestPath = `${rootfs}.manifest.json`;
  const manifest = await readManifest(manifestPath);
  if (manifest === undefined) {
    problems.push(
      `rootfs image ${rootfs} has no build manifest (${manifestPath}); it predates the current brevi and may lack required guest tools such as the codex CLI; ${REBUILD_HINT}`,
    );
  } else if (manifest.version !== ROOTFS_MANIFEST_VERSION) {
    problems.push(
      `rootfs image ${rootfs} was built with manifest version ${manifest.version}, but this brevi expects version ${ROOTFS_MANIFEST_VERSION}; ${REBUILD_HINT}`,
    );
  }

  return problems;
}

async function looksLikeExt4(rootfs: string): Promise<boolean> {
  let handle;
  try {
    handle = await open(rootfs, "r");
    const buf = Buffer.alloc(2);
    const { bytesRead } = await handle.read(buf, 0, 2, EXT4_MAGIC_OFFSET);
    return bytesRead === 2 && buf.equals(EXT4_MAGIC_BYTES);
  } catch {
    return false;
  } finally {
    await handle?.close();
  }
}

async function readManifest(manifestPath: string): Promise<{ version: unknown } | undefined> {
  try {
    const raw = await readFile(manifestPath, "utf8");
    const parsed: unknown = JSON.parse(raw);
    if (typeof parsed !== "object" || parsed === null) return undefined;
    return parsed as { version: unknown };
  } catch {
    return undefined;
  }
}

/**
 * Networking problems that block Firecracker regardless of the base preflight: missing
 * tap devices and disabled IPv4 forwarding. Skipped on non-Linux hosts; the base checks
 * already report the platform problem there.
 */
export async function collectFirecrackerNetworkProblems(concurrency: number): Promise<string[]> {
  if (process.platform !== "linux") return [];

  const problems: string[] = [];
  const pointer =
    "run brevi setup's networking step or packages/sandbox/scripts/setup-network.sh (tap devices and rules do not persist across reboots, so this is needed again after every restart)";

  // Root creates tap devices on demand (see ensureTapDevice in ./network.ts), so missing
  // taps are only a problem for a non-root process.
  if (process.getuid?.() !== 0) {
    const missing: string[] = [];
    for (let i = 0; i < concurrency; i++) {
      if (!(await fileExists(`/sys/class/net/brevi-tap${i}`))) missing.push(`brevi-tap${i}`);
    }
    if (missing.length > 0) {
      problems.push(`tap devices missing: ${missing.join(", ")}; ${pointer}`);
    }
  }

  if (!(await ipForwardEnabled())) {
    problems.push(`IPv4 forwarding is disabled; ${pointer}`);
  }

  return problems;
}

async function ipForwardEnabled(): Promise<boolean> {
  try {
    return (await readFile("/proc/sys/net/ipv4/ip_forward", "utf8")).trim() === "1";
  } catch {
    return false;
  }
}

/**
 * The complete Firecracker preflight: everything collectFirecrackerProblems checks, plus
 * networking. This is what provider selection and `brevi doctor` should use; auto-mode and
 * explicit-provider validation both need the network checks, not just the base ones.
 */
export async function collectFirecrackerPreflightProblems(
  config: FirecrackerConfig,
  concurrency: number,
): Promise<string[]> {
  return [
    ...(await collectFirecrackerProblems(config)),
    ...(await collectFirecrackerNetworkProblems(concurrency)),
  ];
}

/**
 * Runs each sandbox as a Firecracker microVM: real kernel-level isolation, at the cost
 * of requiring a Linux host with KVM plus a prepared kernel and rootfs image.
 */
export class FirecrackerProvider implements SandboxProvider {
  readonly name = "firecracker" as const;
  readonly #config: FirecrackerConfig;

  constructor(config: FirecrackerConfig) {
    this.#config = config;
  }

  async ensureAvailable(): Promise<void> {
    const problems = await collectFirecrackerProblems(this.#config);
    if (problems.length === 0) return;
    const remedy =
      process.platform === "linux"
        ? `Run "brevi setup" to provision this host, or see ${SETUP_DOC} for manual setup.`
        : `See ${SETUP_DOC} for what the firecracker provider needs.`;
    throw new Error(
      `The firecracker sandbox provider cannot run on this host:\n${problems
        .map((problem) => `  - ${problem}`)
        .join("\n")}\n${remedy}`,
    );
  }

  async create(options: CreateSandboxOptions): Promise<Sandbox> {
    const rootDir = join(WORKSPACES_DIR, options.id);
    const vm = await bootMicroVm({ id: options.id, rootDir, config: this.#config });
    try {
      const target: SshTarget = {
        keyPath: SSH_KEY_PATH,
        host: vm.network.guestIp,
        user: "root",
      };
      await waitForSsh(target);
      await ensureGuestWorkspace(target);
      return new FirecrackerSandbox({ id: options.id, vm, target, env: options.env ?? {}, rootDir });
    } catch (error) {
      await vm.stop();
      await rm(rootDir, { recursive: true, force: true });
      throw error;
    }
  }

  async rehydrate(options: CreateSandboxOptions): Promise<Sandbox> {
    const rootDir = join(WORKSPACES_DIR, options.id);
    const vm = await bootMicroVm({ id: options.id, rootDir, config: this.#config, reuseRootfs: true });
    try {
      const target: SshTarget = {
        keyPath: SSH_KEY_PATH,
        host: vm.network.guestIp,
        user: "root",
      };
      await waitForSsh(target);
      return new FirecrackerSandbox({ id: options.id, vm, target, env: options.env ?? {}, rootDir });
    } catch (error) {
      // Keep the retained rootfs on disk so a failed resume can be retried.
      await vm.stop();
      throw error;
    }
  }

  async discard(id: string): Promise<void> {
    await rm(join(WORKSPACES_DIR, id), { recursive: true, force: true });
  }
}
