import { rm } from "node:fs/promises";
import { join } from "node:path";
import { WORKSPACES_DIR, type FirecrackerConfig } from "@brevi/shared";
import { fileExists, isReadWritable, resolveBinary, resolveFirecrackerBinary } from "../host.js";
import type { CreateSandboxOptions, Sandbox, SandboxProvider } from "../types.js";
import { ensureGuestWorkspace, FirecrackerSandbox } from "./sandbox.js";
import { SSH_KEY_PATH, waitForSsh, type SshTarget } from "./ssh.js";
import { bootMicroVm } from "./vm.js";

/** Host tools the provider shells out to for networking and file transfer. */
const REQUIRED_TOOLS = ["ip", "ssh", "tar"];

const SETUP_DOC = "packages/sandbox/README.md";

/**
 * Everything stopping this host from booting Firecracker microVMs with the given
 * config, as human-readable problems. Empty means the provider is ready to run.
 */
export async function collectFirecrackerProblems(config: FirecrackerConfig): Promise<string[]> {
  const problems: string[] = [];

  if (process.platform !== "linux") {
    problems.push(
      `firecracker needs KVM, which only exists on Linux (this host is ${process.platform}); use the "process" provider or run brevi inside a Linux VM`,
    );
  }
  if (!(await isReadWritable("/dev/kvm"))) {
    problems.push(
      '/dev/kvm is not readable and writable by this user; load the kvm module and add yourself to the "kvm" group',
    );
  }
  if ((await resolveFirecrackerBinary(config.binary)) === undefined) {
    problems.push(
      `the firecracker binary "${config.binary}" was not found on PATH or in ~/.brevi/bin; install it or set sandbox.firecracker.binary`,
    );
  }
  for (const tool of REQUIRED_TOOLS) {
    if ((await resolveBinary(tool)) === undefined) {
      problems.push(`the "${tool}" command was not found on PATH`);
    }
  }
  if (!(await fileExists(config.kernelImage))) {
    problems.push(`kernel image ${config.kernelImage} is missing`);
  }
  if (!(await fileExists(config.rootfs))) {
    problems.push(
      `rootfs image ${config.rootfs} is missing; build it with packages/sandbox/scripts/build-rootfs.sh`,
    );
  }
  if (!(await fileExists(SSH_KEY_PATH))) {
    problems.push(
      `ssh key ${SSH_KEY_PATH} is missing; it is generated by packages/sandbox/scripts/build-rootfs.sh and must match the key baked into the rootfs`,
    );
  }

  return problems;
}

/**
 * Runs each sandbox as a Firecracker microVM: real kernel-level isolation, at the cost
 * of requiring a Linux host with KVM plus a prepared kernel and rootfs image.
 */
export class FirecrackerProvider implements SandboxProvider {
  readonly name = "firecracker" as const;
  readonly #config: FirecrackerConfig;

  constructor(config: FirecrackerConfig) {
    this.#config = config;
  }

  async ensureAvailable(): Promise<void> {
    const problems = await collectFirecrackerProblems(this.#config);
    if (problems.length === 0) return;
    const remedy =
      process.platform === "linux"
        ? `Run "brevi setup" to provision this host, or see ${SETUP_DOC} for manual setup.`
        : `See ${SETUP_DOC} for what the firecracker provider needs.`;
    throw new Error(
      `The firecracker sandbox provider cannot run on this host:\n${problems
        .map((problem) => `  - ${problem}`)
        .join("\n")}\n${remedy}`,
    );
  }

  async create(options: CreateSandboxOptions): Promise<Sandbox> {
    const rootDir = join(WORKSPACES_DIR, options.id);
    const vm = await bootMicroVm({ id: options.id, rootDir, config: this.#config });
    try {
      const target: SshTarget = {
        keyPath: SSH_KEY_PATH,
        host: vm.network.guestIp,
        user: "root",
      };
      await waitForSsh(target);
      await ensureGuestWorkspace(target);
      return new FirecrackerSandbox({ id: options.id, vm, target, env: options.env ?? {}, rootDir });
    } catch (error) {
      await vm.stop();
      await rm(rootDir, { recursive: true, force: true });
      throw error;
    }
  }

  async rehydrate(options: CreateSandboxOptions): Promise<Sandbox> {
    const rootDir = join(WORKSPACES_DIR, options.id);
    const vm = await bootMicroVm({ id: options.id, rootDir, config: this.#config, reuseRootfs: true });
    try {
      const target: SshTarget = {
        keyPath: SSH_KEY_PATH,
        host: vm.network.guestIp,
        user: "root",
      };
      await waitForSsh(target);
      return new FirecrackerSandbox({ id: options.id, vm, target, env: options.env ?? {}, rootDir });
    } catch (error) {
      // Keep the retained rootfs on disk so a failed resume can be retried.
      await vm.stop();
      throw error;
    }
  }

  async discard(id: string): Promise<void> {
    await rm(join(WORKSPACES_DIR, id), { recursive: true, force: true });
  }
}
